// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/addressbook.proto

package generated_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneType int32

const (
	PhoneType_PHONE_TYPE_UNSPECIFIED PhoneType = 0
	PhoneType_PHONE_TYPE_MOBILE      PhoneType = 1
	PhoneType_PHONE_TYPE_HOME        PhoneType = 2
	PhoneType_PHONE_TYPE_WORK        PhoneType = 3
)

// Enum value maps for PhoneType.
var (
	PhoneType_name = map[int32]string{
		0: "PHONE_TYPE_UNSPECIFIED",
		1: "PHONE_TYPE_MOBILE",
		2: "PHONE_TYPE_HOME",
		3: "PHONE_TYPE_WORK",
	}
	PhoneType_value = map[string]int32{
		"PHONE_TYPE_UNSPECIFIED": 0,
		"PHONE_TYPE_MOBILE":      1,
		"PHONE_TYPE_HOME":        2,
		"PHONE_TYPE_WORK":        3,
	}
)

func (x PhoneType) Enum() *PhoneType {
	p := new(PhoneType)
	*p = x
	return p
}

func (x PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_addressbook_proto_enumTypes[0].Descriptor()
}

func (PhoneType) Type() protoreflect.EnumType {
	return &file_proto_addressbook_proto_enumTypes[0]
}

func (x PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhoneType.Descriptor instead.
func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_proto_addressbook_proto_rawDescGZIP(), []int{0}
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Id            *int32                 `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"` // Unique ID number for this person.
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phones        []*Person_PhoneNumber  `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3,oneof" json:"last_updated,omitempty"`
	OrderToAmount map[string]int32       `protobuf:"bytes,6,rep,name=orderToAmount,proto3" json:"orderToAmount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FavoriteSpot  *DESTINATION           `protobuf:"varint,7,opt,name=favoriteSpot,proto3,enum=DESTINATION,oneof" json:"favoriteSpot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_proto_addressbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_addressbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_addressbook_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Person) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Person) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Person) GetPhones() []*Person_PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *Person) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Person) GetOrderToAmount() map[string]int32 {
	if x != nil {
		return x.OrderToAmount
	}
	return nil
}

func (x *Person) GetFavoriteSpot() DESTINATION {
	if x != nil && x.FavoriteSpot != nil {
		return *x.FavoriteSpot
	}
	return DESTINATION_DESTINATION_UNSPECIFIED
}

type SingularCardinalityDemo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionalField *int32                 `protobuf:"varint,1,opt,name=optionalField,proto3,oneof" json:"optionalField,omitempty"`
	ImplicitField int32                  `protobuf:"varint,2,opt,name=implicitField,proto3" json:"implicitField,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingularCardinalityDemo) Reset() {
	*x = SingularCardinalityDemo{}
	mi := &file_proto_addressbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingularCardinalityDemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingularCardinalityDemo) ProtoMessage() {}

func (x *SingularCardinalityDemo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_addressbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingularCardinalityDemo.ProtoReflect.Descriptor instead.
func (*SingularCardinalityDemo) Descriptor() ([]byte, []int) {
	return file_proto_addressbook_proto_rawDescGZIP(), []int{1}
}

func (x *SingularCardinalityDemo) GetOptionalField() int32 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return 0
}

func (x *SingularCardinalityDemo) GetImplicitField() int32 {
	if x != nil {
		return x.ImplicitField
	}
	return 0
}

// Our address book file is just one of these.
type AddressBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	People        []*Person              `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBook) Reset() {
	*x = AddressBook{}
	mi := &file_proto_addressbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBook) ProtoMessage() {}

func (x *AddressBook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_addressbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBook.ProtoReflect.Descriptor instead.
func (*AddressBook) Descriptor() ([]byte, []int) {
	return file_proto_addressbook_proto_rawDescGZIP(), []int{2}
}

func (x *AddressBook) GetPeople() []*Person {
	if x != nil {
		return x.People
	}
	return nil
}

type PhoneBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumbers  []*Person_PhoneNumber  `protobuf:"bytes,1,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneBook) Reset() {
	*x = PhoneBook{}
	mi := &file_proto_addressbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneBook) ProtoMessage() {}

func (x *PhoneBook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_addressbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneBook.ProtoReflect.Descriptor instead.
func (*PhoneBook) Descriptor() ([]byte, []int) {
	return file_proto_addressbook_proto_rawDescGZIP(), []int{3}
}

func (x *PhoneBook) GetPhoneNumbers() []*Person_PhoneNumber {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

type Person_PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type          PhoneType              `protobuf:"varint,2,opt,name=type,proto3,enum=tutorial.PhoneType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person_PhoneNumber) Reset() {
	*x = Person_PhoneNumber{}
	mi := &file_proto_addressbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person_PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_PhoneNumber) ProtoMessage() {}

func (x *Person_PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_proto_addressbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_PhoneNumber.ProtoReflect.Descriptor instead.
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return file_proto_addressbook_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Person_PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Person_PhoneNumber) GetType() PhoneType {
	if x != nil {
		return x.Type
	}
	return PhoneType_PHONE_TYPE_UNSPECIFIED
}

var File_proto_addressbook_proto protoreflect.FileDescriptor

const file_proto_addressbook_proto_rawDesc = "" +
	"\n" +
	"\x17proto/addressbook.proto\x12\btutorial\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15proto/enum_demo.proto\"\x9b\x04\n" +
	"\x06Person\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x05H\x01R\x02id\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x02R\x05email\x88\x01\x01\x124\n" +
	"\x06phones\x18\x04 \x03(\v2\x1c.tutorial.Person.PhoneNumberR\x06phones\x12B\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\vlastUpdated\x88\x01\x01\x12I\n" +
	"\rorderToAmount\x18\x06 \x03(\v2#.tutorial.Person.OrderToAmountEntryR\rorderToAmount\x125\n" +
	"\ffavoriteSpot\x18\a \x01(\x0e2\f.DESTINATIONH\x04R\ffavoriteSpot\x88\x01\x01\x1aN\n" +
	"\vPhoneNumber\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.tutorial.PhoneTypeR\x04type\x1a@\n" +
	"\x12OrderToAmountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_idB\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_last_updatedB\x0f\n" +
	"\r_favoriteSpot\"|\n" +
	"\x17SingularCardinalityDemo\x12)\n" +
	"\roptionalField\x18\x01 \x01(\x05H\x00R\roptionalField\x88\x01\x01\x12$\n" +
	"\rimplicitField\x18\x02 \x01(\x05R\rimplicitFieldB\x10\n" +
	"\x0e_optionalField\"7\n" +
	"\vAddressBook\x12(\n" +
	"\x06people\x18\x01 \x03(\v2\x10.tutorial.PersonR\x06people\"N\n" +
	"\tPhoneBook\x12A\n" +
	"\rphone_numbers\x18\x01 \x03(\v2\x1c.tutorial.Person.PhoneNumberR\fphoneNumbers*h\n" +
	"\tPhoneType\x12\x1a\n" +
	"\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PHONE_TYPE_MOBILE\x10\x01\x12\x13\n" +
	"\x0fPHONE_TYPE_HOME\x10\x02\x12\x13\n" +
	"\x0fPHONE_TYPE_WORK\x10\x03B\x16Z\x14proto/generated_codeb\x06proto3"

var (
	file_proto_addressbook_proto_rawDescOnce sync.Once
	file_proto_addressbook_proto_rawDescData []byte
)

func file_proto_addressbook_proto_rawDescGZIP() []byte {
	file_proto_addressbook_proto_rawDescOnce.Do(func() {
		file_proto_addressbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_addressbook_proto_rawDesc), len(file_proto_addressbook_proto_rawDesc)))
	})
	return file_proto_addressbook_proto_rawDescData
}

var file_proto_addressbook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_addressbook_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_addressbook_proto_goTypes = []any{
	(PhoneType)(0),                  // 0: tutorial.PhoneType
	(*Person)(nil),                  // 1: tutorial.Person
	(*SingularCardinalityDemo)(nil), // 2: tutorial.SingularCardinalityDemo
	(*AddressBook)(nil),             // 3: tutorial.AddressBook
	(*PhoneBook)(nil),               // 4: tutorial.PhoneBook
	(*Person_PhoneNumber)(nil),      // 5: tutorial.Person.PhoneNumber
	nil,                             // 6: tutorial.Person.OrderToAmountEntry
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(DESTINATION)(0),                // 8: DESTINATION
}
var file_proto_addressbook_proto_depIdxs = []int32{
	5, // 0: tutorial.Person.phones:type_name -> tutorial.Person.PhoneNumber
	7, // 1: tutorial.Person.last_updated:type_name -> google.protobuf.Timestamp
	6, // 2: tutorial.Person.orderToAmount:type_name -> tutorial.Person.OrderToAmountEntry
	8, // 3: tutorial.Person.favoriteSpot:type_name -> DESTINATION
	1, // 4: tutorial.AddressBook.people:type_name -> tutorial.Person
	5, // 5: tutorial.PhoneBook.phone_numbers:type_name -> tutorial.Person.PhoneNumber
	0, // 6: tutorial.Person.PhoneNumber.type:type_name -> tutorial.PhoneType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_addressbook_proto_init() }
func file_proto_addressbook_proto_init() {
	if File_proto_addressbook_proto != nil {
		return
	}
	file_proto_enum_demo_proto_init()
	file_proto_addressbook_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_addressbook_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_addressbook_proto_rawDesc), len(file_proto_addressbook_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_addressbook_proto_goTypes,
		DependencyIndexes: file_proto_addressbook_proto_depIdxs,
		EnumInfos:         file_proto_addressbook_proto_enumTypes,
		MessageInfos:      file_proto_addressbook_proto_msgTypes,
	}.Build()
	File_proto_addressbook_proto = out.File
	file_proto_addressbook_proto_goTypes = nil
	file_proto_addressbook_proto_depIdxs = nil
}
