// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/any_demo.proto

package generated_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnyDemo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Details       *anypb.Any             `protobuf:"bytes,2,opt,name=details,proto3,oneof" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyDemo) Reset() {
	*x = AnyDemo{}
	mi := &file_proto_any_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyDemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyDemo) ProtoMessage() {}

func (x *AnyDemo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_any_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyDemo.ProtoReflect.Descriptor instead.
func (*AnyDemo) Descriptor() ([]byte, []int) {
	return file_proto_any_demo_proto_rawDescGZIP(), []int{0}
}

func (x *AnyDemo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AnyDemo) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_any_demo_proto protoreflect.FileDescriptor

const file_proto_any_demo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/any_demo.proto\x1a\x19google/protobuf/any.proto\"l\n" +
	"\aAnyDemo\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x123\n" +
	"\adetails\x18\x02 \x01(\v2\x14.google.protobuf.AnyH\x01R\adetails\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_detailsB\x16Z\x14proto/generated_codeb\x06proto3"

var (
	file_proto_any_demo_proto_rawDescOnce sync.Once
	file_proto_any_demo_proto_rawDescData []byte
)

func file_proto_any_demo_proto_rawDescGZIP() []byte {
	file_proto_any_demo_proto_rawDescOnce.Do(func() {
		file_proto_any_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_any_demo_proto_rawDesc), len(file_proto_any_demo_proto_rawDesc)))
	})
	return file_proto_any_demo_proto_rawDescData
}

var file_proto_any_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_any_demo_proto_goTypes = []any{
	(*AnyDemo)(nil),   // 0: AnyDemo
	(*anypb.Any)(nil), // 1: google.protobuf.Any
}
var file_proto_any_demo_proto_depIdxs = []int32{
	1, // 0: AnyDemo.details:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_any_demo_proto_init() }
func file_proto_any_demo_proto_init() {
	if File_proto_any_demo_proto != nil {
		return
	}
	file_proto_any_demo_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_any_demo_proto_rawDesc), len(file_proto_any_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_any_demo_proto_goTypes,
		DependencyIndexes: file_proto_any_demo_proto_depIdxs,
		MessageInfos:      file_proto_any_demo_proto_msgTypes,
	}.Build()
	File_proto_any_demo_proto = out.File
	file_proto_any_demo_proto_goTypes = nil
	file_proto_any_demo_proto_depIdxs = nil
}
