// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/enum_demo.proto

package generated_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_enum_demo_proto protoreflect.FileDescriptor

const file_proto_enum_demo_proto_rawDesc = "" +
	"\n" +
	"\x15proto/enum_demo.proto\x1a\x1fproto/enums/new_enum_demo.protoB\x16Z\x14proto/generated_codeP\x00b\x06proto3"

var file_proto_enum_demo_proto_goTypes = []any{}
var file_proto_enum_demo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enum_demo_proto_init() }
func file_proto_enum_demo_proto_init() {
	if File_proto_enum_demo_proto != nil {
		return
	}
	file_proto_enums_new_enum_demo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enum_demo_proto_rawDesc), len(file_proto_enum_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enum_demo_proto_goTypes,
		DependencyIndexes: file_proto_enum_demo_proto_depIdxs,
	}.Build()
	File_proto_enum_demo_proto = out.File
	file_proto_enum_demo_proto_goTypes = nil
	file_proto_enum_demo_proto_depIdxs = nil
}
