// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/oneof_demo.proto

package generated_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneofDemo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pan   *string                `protobuf:"bytes,1,opt,name=pan,proto3,oneof" json:"pan,omitempty"`
	// Types that are valid to be assigned to AadharOrRegistration:
	//
	//	*OneofDemo_Aadhar
	//	*OneofDemo_Registration
	AadharOrRegistration isOneofDemo_AadharOrRegistration `protobuf_oneof:"aadhar_or_registration"`
	Zip                  *string                          `protobuf:"bytes,4,opt,name=zip,proto3,oneof" json:"zip,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OneofDemo) Reset() {
	*x = OneofDemo{}
	mi := &file_proto_oneof_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofDemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofDemo) ProtoMessage() {}

func (x *OneofDemo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oneof_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofDemo.ProtoReflect.Descriptor instead.
func (*OneofDemo) Descriptor() ([]byte, []int) {
	return file_proto_oneof_demo_proto_rawDescGZIP(), []int{0}
}

func (x *OneofDemo) GetPan() string {
	if x != nil && x.Pan != nil {
		return *x.Pan
	}
	return ""
}

func (x *OneofDemo) GetAadharOrRegistration() isOneofDemo_AadharOrRegistration {
	if x != nil {
		return x.AadharOrRegistration
	}
	return nil
}

func (x *OneofDemo) GetAadhar() string {
	if x != nil {
		if x, ok := x.AadharOrRegistration.(*OneofDemo_Aadhar); ok {
			return x.Aadhar
		}
	}
	return ""
}

func (x *OneofDemo) GetRegistration() string {
	if x != nil {
		if x, ok := x.AadharOrRegistration.(*OneofDemo_Registration); ok {
			return x.Registration
		}
	}
	return ""
}

func (x *OneofDemo) GetZip() string {
	if x != nil && x.Zip != nil {
		return *x.Zip
	}
	return ""
}

type isOneofDemo_AadharOrRegistration interface {
	isOneofDemo_AadharOrRegistration()
}

type OneofDemo_Aadhar struct {
	Aadhar string `protobuf:"bytes,2,opt,name=aadhar,proto3,oneof"`
}

type OneofDemo_Registration struct {
	Registration string `protobuf:"bytes,3,opt,name=registration,proto3,oneof"`
}

func (*OneofDemo_Aadhar) isOneofDemo_AadharOrRegistration() {}

func (*OneofDemo_Registration) isOneofDemo_AadharOrRegistration() {}

var File_proto_oneof_demo_proto protoreflect.FileDescriptor

const file_proto_oneof_demo_proto_rawDesc = "" +
	"\n" +
	"\x16proto/oneof_demo.proto\"\xa3\x01\n" +
	"\tOneofDemo\x12\x15\n" +
	"\x03pan\x18\x01 \x01(\tH\x01R\x03pan\x88\x01\x01\x12\x18\n" +
	"\x06aadhar\x18\x02 \x01(\tH\x00R\x06aadhar\x12$\n" +
	"\fregistration\x18\x03 \x01(\tH\x00R\fregistration\x12\x15\n" +
	"\x03zip\x18\x04 \x01(\tH\x02R\x03zip\x88\x01\x01B\x18\n" +
	"\x16aadhar_or_registrationB\x06\n" +
	"\x04_panB\x06\n" +
	"\x04_zipB\x16Z\x14proto/generated_codeb\x06proto3"

var (
	file_proto_oneof_demo_proto_rawDescOnce sync.Once
	file_proto_oneof_demo_proto_rawDescData []byte
)

func file_proto_oneof_demo_proto_rawDescGZIP() []byte {
	file_proto_oneof_demo_proto_rawDescOnce.Do(func() {
		file_proto_oneof_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oneof_demo_proto_rawDesc), len(file_proto_oneof_demo_proto_rawDesc)))
	})
	return file_proto_oneof_demo_proto_rawDescData
}

var file_proto_oneof_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_oneof_demo_proto_goTypes = []any{
	(*OneofDemo)(nil), // 0: OneofDemo
}
var file_proto_oneof_demo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_oneof_demo_proto_init() }
func file_proto_oneof_demo_proto_init() {
	if File_proto_oneof_demo_proto != nil {
		return
	}
	file_proto_oneof_demo_proto_msgTypes[0].OneofWrappers = []any{
		(*OneofDemo_Aadhar)(nil),
		(*OneofDemo_Registration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oneof_demo_proto_rawDesc), len(file_proto_oneof_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_oneof_demo_proto_goTypes,
		DependencyIndexes: file_proto_oneof_demo_proto_depIdxs,
		MessageInfos:      file_proto_oneof_demo_proto_msgTypes,
	}.Build()
	File_proto_oneof_demo_proto = out.File
	file_proto_oneof_demo_proto_goTypes = nil
	file_proto_oneof_demo_proto_depIdxs = nil
}
