// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/person.service.proto

package generated_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *string                `protobuf:"bytes,1,opt,name=login,proto3,oneof" json:"login,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Q             *string                `protobuf:"bytes,3,opt,name=q,proto3,oneof" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_person_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_person_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *SearchRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *SearchRequest) GetQ() string {
	if x != nil && x.Q != nil {
		return *x.Q
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *string                `protobuf:"bytes,1,opt,name=login,proto3,oneof" json:"login,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Zip           *string                `protobuf:"bytes,3,opt,name=zip,proto3,oneof" json:"zip,omitempty"`
	Country       *string                `protobuf:"bytes,4,opt,name=country,proto3,oneof" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_person_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_person_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_person_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *SearchResponse) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *SearchResponse) GetZip() string {
	if x != nil && x.Zip != nil {
		return *x.Zip
	}
	return ""
}

func (x *SearchResponse) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

var File_proto_person_service_proto protoreflect.FileDescriptor

const file_proto_person_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/person.service.proto\"r\n" +
	"\rSearchRequest\x12\x19\n" +
	"\x05login\x18\x01 \x01(\tH\x00R\x05login\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x11\n" +
	"\x01q\x18\x03 \x01(\tH\x02R\x01q\x88\x01\x01B\b\n" +
	"\x06_loginB\b\n" +
	"\x06_emailB\x04\n" +
	"\x02_q\"\xa4\x01\n" +
	"\x0eSearchResponse\x12\x19\n" +
	"\x05login\x18\x01 \x01(\tH\x00R\x05login\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x15\n" +
	"\x03zip\x18\x03 \x01(\tH\x02R\x03zip\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x04 \x01(\tH\x03R\acountry\x88\x01\x01B\b\n" +
	"\x06_loginB\b\n" +
	"\x06_emailB\x06\n" +
	"\x04_zipB\n" +
	"\n" +
	"\b_country2:\n" +
	"\rPersonService\x12)\n" +
	"\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponseB\x16Z\x14proto/generated_codeb\x06proto3"

var (
	file_proto_person_service_proto_rawDescOnce sync.Once
	file_proto_person_service_proto_rawDescData []byte
)

func file_proto_person_service_proto_rawDescGZIP() []byte {
	file_proto_person_service_proto_rawDescOnce.Do(func() {
		file_proto_person_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_person_service_proto_rawDesc), len(file_proto_person_service_proto_rawDesc)))
	})
	return file_proto_person_service_proto_rawDescData
}

var file_proto_person_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_person_service_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: SearchRequest
	(*SearchResponse)(nil), // 1: SearchResponse
}
var file_proto_person_service_proto_depIdxs = []int32{
	0, // 0: PersonService.Search:input_type -> SearchRequest
	1, // 1: PersonService.Search:output_type -> SearchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_person_service_proto_init() }
func file_proto_person_service_proto_init() {
	if File_proto_person_service_proto != nil {
		return
	}
	file_proto_person_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_person_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_person_service_proto_rawDesc), len(file_proto_person_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_person_service_proto_goTypes,
		DependencyIndexes: file_proto_person_service_proto_depIdxs,
		MessageInfos:      file_proto_person_service_proto_msgTypes,
	}.Build()
	File_proto_person_service_proto = out.File
	file_proto_person_service_proto_goTypes = nil
	file_proto_person_service_proto_depIdxs = nil
}
